### ISSUE TITLE
[Suggestion] Add file generation loading bar

### ISSUE THREAD

**Issue by ISenseAura** [potato-lulw/assignment-buddy#1]
Instead of "Sending" button, show a loading bar which displays the assignment generation progress (as shown in the attached image).
to track the progress, you can use
 timeRequiredToGenerate = (numberOfQuestions * 10.5) secs

show progress percentage inside the loading bar

reference : https://codepen.io/manz/pen/GRxJgZZ

![Screenshot 2024-01-26 193927](https://github.com/potato-lulw/assignment-buddy/assets/33085835/1e3f4807-c4cf-4b60-8f9c-af5f064854de)

**Comment by potato-lulw** [comment]
Very good suggestion. I will definitly implement it soon.
