### ISSUE TITLE
[Bug] Passing undefined as a question to the server 

### ISSUE THREAD

**Issue by ISenseAura** [potato-lulw/assignment-buddy#2]
Pressing enter after writing the last question adds one more empty question which leads to addition of  "undefined" to the qs array

Fix : look for invalid questions in the qs array and remove it from the array. Add checks for valid questions.

Invalid Questions : undefined, null, numbers, " " , strings with length < 5, etc.

**Comment by potato-lulw** [comment]
Thank you for the bug report. I have added a valid question checking function which returns valid questions from the list of questions.

```
const isValidQuestion = (question) => {
    // Check if the question is a valid string
    if (typeof question !== 'string') {
        return false;
    }

    // Remove leading and trailing whitespaces
    const trimmedQuestion = question.trim();

    // Check if the question is not empty and has a length of at least 5 characters
    if (trimmedQuestion.length < 5) {
        return false;
    }

    // Check if the question is not "undefined" or "null"
    if (trimmedQuestion.toLowerCase() === 'undefined' || trimmedQuestion.toLowerCase() === 'null') {
        return false;
    }

    return true;
};
```

RESULTS : 
![image](https://github.com/potato-lulw/assignment-buddy/assets/96940311/aba1e197-31fc-46e1-8139-6cc2673fe287)
![image](https://github.com/potato-lulw/assignment-buddy/assets/96940311/f177059b-5e14-45e8-932f-5ec01601e6ca)
