### ISSUE TITLE
API connection issue

### ISSUE THREAD

**Issue by RanjanH** [potato-lulw/assignment-buddy#4]
There is an issue in GET and POST method
![Screenshot 2024-01-27 185642](https://github.com/potato-lulw/assignment-buddy/assets/84950556/4df7694c-66d0-4a21-97f3-c176e1bb344a)

**Comment by ISenseAura** [comment]
provide methods to reproduce the mentioned error

**Comment by RanjanH** [comment]
This error occurs while I am sending the questions in the "add assignment" page i.e. i followed the following steps:
1- Go to the "add assignment" page 
2- Pick the subject name, assignment number and write the intended questions
    Subject Name - BIS
    Assignment Number - 1
    Question - 1) What is BIS
3- Then click the "Send it" button

**Comment by ISenseAura** [comment]
After reproducing the bug and investing further, i found out that it was an issue on the server side which has been fixed and has been tested.
thanks.
